# Generated by Django 3.1.7 on 2021-04-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.TextField()),
                ('title', models.TextField(max_length=200)),
                ('type', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_639_1', models.TextField(max_length=200)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(to='home.Crew'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.TextField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='imdb_id',
            field=models.TextField(max_length=9, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='home.Cast'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(to='home.ProductionCompany'),
        ),
        migrations.DeleteModel(
            name='Credits',
        ),
        migrations.AddField(
            model_name='alternativetitle',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(to='home.SpokenLanguage'),
        ),
    ]
