# Generated by Django 3.1.7 on 2021-04-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210420_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='MovieDetails',
        ),
    ]
