# Generated by Django 3.1.7 on 2021-04-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210421_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='status',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
