# Generated by Django 3.1.7 on 2021-04-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210421_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='People',
        ),
    ]
