# Generated by Django 3.1.7 on 2021-04-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210423_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, # noqa
                                       to='home.people'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, # noqa
                                       to='home.people'),
        ),
    ]
