# Generated by Django 3.1.7 on 2021-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210423_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
