# Generated by Django 3.1.7 on 2021-04-23 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210423_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='id',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='id',
        ),
        migrations.AlterField(
            model_name='cast',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, # noqa
                                       primary_key=True, serialize=False,
                                       to='home.people'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, # noqa
                                       primary_key=True, serialize=False,
                                       to='home.people'),
        ),
    ]
