# Generated by Django 3.1.7 on 2021-04-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210423_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='department',
            field=models.TextField(),
        ),
    ]
