# Generated by Django 3.1.7 on 2021-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210423_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='job',
            field=models.TextField(),
        ),
    ]
