# Generated by Django 3.1.7 on 2021-04-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210423_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='person',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='crew',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
    ]
