# Generated by Django 3.1.7 on 2021-04-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210423_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.TextField()),
                ('job', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people')),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.TextField()),
                ('order', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people')),
            ],
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='cast',
            field=models.ManyToManyField(to='home.Cast'),
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='crew',
            field=models.ManyToManyField(to='home.Crew'),
        ),
    ]
