# Generated by Django 3.1.7 on 2021-04-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210423_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternativeTitle',
        ),
    ]
