# Generated by Django 3.1.7 on 2021-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_alternativetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedetails',
            name='revenue',
            field=models.BigIntegerField(null=True),
        ),
    ]
